apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0  # disables deployment rollback, but using helm for that anyway
  {{- if eq .Values.replicaCount 1.0 }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0  # Avoid Terminating and ContainerCreating at the same time
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
#      initContainers:
#        - name: {{ .Chart.Name }}-migrate
#          image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
#          command: ['/bin/sh', '-c', 'manage.py check --deploy && manage.py migrate']
#          {{- if .Values.envSecret }}
#          envFrom:
#            - secretRef:
#                name: {{ .Values.envSecret }}
#          {{- end }}
#          {{- if .Values.env }}
#          env:
#            {{- range $key, $value := .Values.env }}
#            - name: {{ $key | quote }}
#              value: {{ $value | quote }}
#            {{- end }}
#          {{- end }}
#          securityContext:
#            allowPrivilegeEscalation: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: stats
              containerPort: 1717
          {{- if .Values.envSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
#          volumeMounts:
#            - name: media
#              mountPath: /app/web/media
          livenessProbe:
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: /api/health/ip
              port: 8080
              httpHeaders:
                - name: Host
                  value: localhost
          readinessProbe:
            initialDelaySeconds: 1  # Don't get traffic too soon.
            httpGet:
              path: /api/health/
              port: 8080
              httpHeaders:
                - name: Host
                  value: localhost
          lifecycle:
            preStop:
              exec:
                # https://github.com/kubernetes/contrib/issues/1140
                # This hack avoids 0% downtime during deploys.
                # After the preStop, containers receive a SIGTERM meaning:
                # "cleanup what you're doing and stop accepting new work".
                # Yet traffic may still briefly be sent to it by the ingress
                # controller. This hack delays that SIGTERM moment so the new
                # container is already actively used to handle traffic.
                command: ["sleep", "15"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
#      volumes:
#        - name: media
#        {{- if .Values.persistence.enabled }}
#          persistentVolumeClaim:
#            claimName: {{ .Values.persistence.media.existingClaim | default (printf "%s-media" (include "fullname" .)) }}
#        {{- else }}
#          emptyDir: {}
#        {{- end }}
