---
image: edoburu/gitlab-kubernetes-client:kubectl-1.9.2-helm-2.8.0

stages:
- package
- push
- deploy

before_script:
  # Allow sh substitution
  # CI_COMMIT_TAG is only filled for tags.
  # CI_COMMIT_REF_NAME can be a tag or branch name
  - export IMAGE_TAG=${CI_COMMIT_TAG:-git_${CI_COMMIT_REF_NAME}_$CI_COMMIT_SHA}$(test "$CI_JOB_TRIGGERED" = "true" && date "+_trigger%s")
  - export GIT_VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}@$CI_COMMIT_SHA

package:
  tags:
  - container-builder
  #services:
  #- postgres:latest
  #- redis:latest
  stage: package
  script:
  - echo "data_file=/tmp/coveragerc" >> src/.coveragerc  # Fix write issues for coverage
  - docker build --pull --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG --build-arg GIT_VERSION=$GIT_VERSION .
  - docker run --rm $CI_REGISTRY_IMAGE:$IMAGE_TAG py.test --cov

push image:
  tags:
  - container-builder
  stage: push
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  only:
  - tags
  - master

deploy to production:
  stage: deploy
  tags:
  - container-builder
  environment:
    name: production
    url: https://demo.django-fluent.org/
  script:
    # This is a fancy way to execute:
    # helm upgrade --install --tiller-namespace fluentdemo --namespace fluentdemo --reset-values fluentdemo-prd ./deployment/chart/ -f deployment/values-prd.yml --set=imageTag=$IMAGE_TAG
    # By default we'd use the docker hub registry, but override in this case with the GitLab container registry.
  - ./deployment/deploy-env prd --set=imageRepository=$CI_REGISTRY_IMAGE
  only:
  - tags
  - triggers
  - schedules
