---
stages:
- build
- push

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}

build_image:
  tags:
  - container-builder
  #services:
  #- postgres:latest
  #- redis:latest
  stage: build
  script:
  - docker build -t $IMAGE_TAG .
  - docker run --rm $IMAGE_TAG /app/src/runtests.py

push_image:
  stage: push
  tags:
  - container-builder
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $IMAGE_TAG
  only:
  - tags
