sudo: false
language: python
cache: pip

python:
- '2.7'
#- '3.4'  # broken by twitterfeed package

env:
- DJANGO_SETTINGS_MODULE=fluentdemo.settings.unittest

install:
- pip install -U pip wheel setuptools
- pip install -r src/requirements/unittest.txt

before_script: cd src
script:
- coverage run ./manage.py check
- py.test --cov --cov-append --nomigrations

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    ## TODO: Replace this for your own projects
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
#  slack:
#    secure: ....
#    on_success: never
#    on_failure: always
