#!/bin/sh
KUBE_NAMESPACE="healinginpractice"
cd `dirname $0`
for file in secrets/*.secrets
do
  basename="$(basename $file)"
  (
    echo "apiVersion: v1"
    echo "kind: Secret"
    kubectl create secret generic "${basename%.*}" --namespace="$KUBE_NAMESPACE" --from-env-file="$file" --dry-run -o yaml ) | kubectl apply -f -
done
