#!/bin/sh
set -e
cd `dirname $0`

# Simulate CI variables when running manually:
source ./deploy-env.conf
export KUBE_NAMESPACE="${KUBE_NAMESPACE:-$PROJECT_NAMESPACE}"
export CI_PROJECT_PATH_SLUG="${CI_PROJECT_PATH_SLUG:-$PROJECT_NAME}"
export CI_ENVIRONMENT_SLUG="${CI_ENVIRONMENT_SLUG:-$PROJECT_ENVIRONMENT_SLUG}"
export CI_COMMIT_REF_NAME="${CI_COMMIT_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
export CI_COMMIT_SHA="${CI_COMMIT_SHA:-$(git rev-parse HEAD)}"

if [ -z "$1" ]; then
  echo "Usage: $0 env [helm-args]" >&2
  exit 1
fi

ENV="$1"; shift
test -n "$IMAGE_TAG" || export IMAGE_TAG=${CI_COMMIT_TAG:-git_${CI_COMMIT_REF_NAME}_$CI_COMMIT_SHA}
RELEASE_NAME="$RELEASE_NAME_PREFIX-$ENV"

./create-release $RELEASE_NAME ./chart/ -f "values-$ENV.yml" --set="imageTag=$IMAGE_TAG" "$@"

if [ -z "$CI_ENVIRONMENT_URL" ]; then
  exit 0
fi

./wait-for-release $RELEASE_NAME $CI_ENVIRONMENT_URL
