---
image:
  # registry is set via --set argument
  pullSecrets:
  - name: gitlab-registry
envSecret: "fluentdemo-prd-env"
env:
  ALLOWED_HOSTS: "demo.django-fluent.org"
  CSRF_COOKIE_SECURE: "true"
  SESSION_COOKIE_SECURE: "true"
securityContext:
  runAsUser: 1017  # fluentdemo on experience
  fsGroup: 1001  # wsgiusers on experience
persistence:
  enabled: false
readinessProbe:
  enabled: false
livenessProbe:
  periodSeconds: 300
ingress:
  enabled: true
  hosts:
  - demo.django-fluent.org
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
    - demo.django-fluent.org
