---
envSecret: "fluentdemo-env-prd"
env:
  ALLOWED_HOSTS: "demo.django-fluent.org,localhost"
  CSRF_COOKIE_SECURE: "true"
  SESSION_COOKIE_SECURE: "true"
nodeSelector:
  purpose: apps
ingress:
  enabled: true
  hosts:
  - demo.django-fluent.org
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    #kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
    - demo.django-fluent.org
