apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: fluentdemo
  environment: prd
  release: fluentdemo-prd

configMapGenerator:
  - literals:
      - ALLOWED_HOSTS=demo.django-fluent.org
      - CSRF_COOKIE_SECURE=true
      - ROBOTS_TXT_DISALLOW_ALL=false
      - SENTRY_ENVIRONMENT=production
      - SESSION_COOKIE_SECURE=true
    name: fluentdemo-env

namespace: fluentdemo
nameSuffix: -prd

patchesStrategicMerge:
  - patches.yml

resources:
  - ../../base
  - ingress.yml
