apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: fluentdemo
  environment: tst
  release: fluentdemo-tst

configMapGenerator:
  - literals:
      - ALLOWED_HOSTS=demo-tst.django-fluent.org
      - CSRF_COOKIE_SECURE=true
      - ROBOTS_TXT_DISALLOW_ALL=true
      - SENTRY_ENVIRONMENT=test
      - SESSION_COOKIE_SECURE=true
    name: fluentdemo-env

namespace: fluentdemo
nameSuffix: -tst

patchesStrategicMerge:
  - patches.yml

resources:
  - ../../base
  - ingress.yml
