apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluentdemo
spec:
  rules:
    - host: fluentdemo.localk8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fluentdemo
                port:
                  number: 80
