apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: fluentdemo
  environment: dev
  release: fluentdemo-dev

configMapGenerator:
  - literals:
      - ALLOW_HTTP=1
      - ALLOWED_HOSTS=fluentdemo.localk8s
      - CSRF_COOKIE_SECURE=false
      - ROBOTS_TXT_DISALLOW_ALL=true
      - SESSION_COOKIE_SECURE=false
    name: fluentdemo-env

namespace: fluentdemo
nameSuffix: -dev

patchesStrategicMerge:
  - patches.yml

resources:
  - ../../base
  - ingress.yml
